name: Deploy to Production

on:
  push:
    branches: [master]
    paths:
      - 'drizzle/**'
      - 'public/**'
      - 'src/**'
      - 'worker/**'
      - 'index.html'
      - 'wrangler.jsonc'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.ts'
      - 'tsconfig*.json'
      - 'worker-configuration.d.ts'    
  workflow_dispatch:

concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build and deploy to production
        run: npm run deploy:prod
        env:
          CLOUDFLARE_API_TOKEN : ${{ secrets.CLOUDFLARE_API_TOKEN  }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  notify-production-success:
    name: Notify Production Success  
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: success()
    
    steps:
      - name: Notify success
        run: |
          echo "Production deployment successful!"
          echo "URL: https://secure-link-production.secure-link.workers.dev"